### ISSUE TITLE
Ida.wll is missing

### ISSUE THREAD

**Issue by jvoisin** [ynvb/DIE#18]
Hello,
it seems that you uploaded your [ida.exe]( https://github.com/ynvb/DIE/blob/8219aaf309400d44afb561c5cb5826d3a519e71e/ida67_patch.zip ) files, and you forgot to give the `ida.wll` file along with it.

Can you please upload it somewhere?

Thank you.

**Comment by techbliss** [comment]
yeah ida64.wll is missing also

**Comment by mrexodia** [comment]
lol

**Comment by ynvb** [comment]
Ida67 patch was removed.

**Comment by jvoisin** [comment]
No it wasn't ;)
