### ISSUE TITLE
IDA v6.6 Failed to initialize DIE

### ISSUE THREAD

**Issue by fallenwinter** [ynvb/DIE#21]
I get a message when initialization, "Failed to initialize DIE.", it raise an exception MenuHelperException("Failed adding menu item.")

**Comment by tmr232** [comment]
Is the top-level DIE menu created?

**Comment by fallenwinter** [comment]
No, I think the except handler delete the menu items once the MenuHelperException occurred.

**Comment by tmr232** [comment]
Can you comment out the deletion or just run the menu creation code? It would help to know if the menu gets created or not. 
You can also try reading the MenuManager docs on http://sark.readthedocs.org/en/latest/api/UI.html#menu-manager

**Comment by fallenwinter** [comment]
I use IDA python command line to run the part of menu creation code only, and I get the following result

Python>die_manager = DieManager()
Logfile created at C:\Users\CSI-x64\Desktop\DIE.log
Initializing plugin <class 'yapsy_loaded_plugin_BasicStringParser_2.BasicStringParser'>
Initializing plugin <class 'yapsy_loaded_plugin_HandleParser_2.HandleParser'>
Initializing plugin <class 'yapsy_loaded_plugin_BoolParser_2.BoolParser'>
Initializing plugin <class 'yapsy_loaded_plugin_StringParser_2.StringParser'>
Initializing plugin <class 'yapsy_loaded_plugin_FunctionParser_2.FunctionParser'>
Initializing plugin <class 'yapsy_loaded_plugin_ModuleParser_2.ModuleParser'>
Python>die_manager.add_menu_items()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 121, in add_menu_items
  File "<string>", line 112, in add_menu_item_helper
__main__.MenuHelperException: Failed adding menu item.

**Comment by tmr232** [comment]
Try and run the following code:

```python
import sark

menu_manager = sark.ui.MenuManager()
menu_manager.add_menu("Some menu name")
```

Does a menu get created?

If the answer is yes, you can try changing [line 157 in DIE.py](https://github.com/ynvb/DIE/blob/master/DIE.py#L157) to create a menu named `"DIE"` instead of `"&DIE"`.

**Comment by ynvb** [comment]
IDA 6.6 is no longer supported.
