### ISSUE TITLE
Does not load, no errors. IDA 6.95

### ISSUE THREAD

**Issue by TurianNaptime** [ynvb/DIE#33]
I followed the pre-compiled steps, but there is no "DIE" meny choice for me. 
I've set a system variable "DIEDIR" to "C:\Program Files (x86)\IDA 6.95\plugins\DIE-master" (tried to add the "\DIE" as well), and copied the die_proxy.py to "C:\Program Files (x86)\IDA 6.95\plugins". I've installed new version on Python27 with pip, and installed the requirements. 
Running Win10.

Any idea what to try out? 😃

**Comment by TurianNaptime** [comment]
Alright major update. First off, I'm stupid and didn't see that that it printed the error in the output window in IDA. Secondly I've got PyQt5, and I think sark is to blame. I've read a lot of documentations, but I haven't found a work around. 
The error is:

die_proxy.py: 'module' object has no attribute 'QDialog'
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.95\python\ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files (x86)/IDA 6.95/plugins/die_proxy.py", line 13, in <module>
    plugin = imp.load_source(__name__, plugin_path)
  File "C:\Program Files (x86)\IDA 6.95\plugins\DIE-master\DIE.py", line 32, in <module>
    from DIE.UI.AboutScreen import AboutWindow
  File "C:\Program Files (x86)\IDA 6.95\plugins\DIE-master\DIE\UI\AboutScreen.py", line 10, in <module>
    class AboutWindow(QtGui.QDialog):
AttributeError: 'module' object has no attribute 'QDialog'

This is not surprising since PyQt4 and 5 are somewhat different.

**Comment by ynvb** [comment]
Fixed in [UI Fix](https://github.com/ynvb/DIE/commit/a36171c9d8578f744a02802d477715ec42cbe4b1)
